// Generated by LiveScript 1.2.0
var colors, Padnews;
colors = require('colors');
Padnews = require('padnews');
new Padnews('sgyfCRGiBZC', 'g0v').run(5000, function(event, msg){
  var prefix, i$, ref$, len$, p, results$ = [];
  prefix = event === 'update' ? '更新 '.yellow : '';
  console.log(((prefix + "" + msg.time.magenta + " ") + ("[" + (msg.location || '？？') + "]").green).bold);
  for (i$ = 0, len$ = (ref$ = msg.content).length; i$ < len$; ++i$) {
    p = ref$[i$];
    results$.push(console.log(p + "\n"));
  }
  return results$;
});